---
name: awscliv2

instance_groups:
- name: awscliv2
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: awscliv2
    release: awscli2
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: awscli2
  sha1: c210d4d624cc5cdf19d830254e49360d7189758c
  stemcell:
    os: ubuntu-bionic
    version: "1.59"
  url: https://github.com/starkandwayne/awscli2-boshrelease/releases/download/v1.0.6/awscli2-1.0.6.tgz
  version: 1.0.6
