---
name: awscliv2

instance_groups:
- name: awscliv2
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: awscliv2
    release: awscli2
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: awscli2
  sha1: 618d81c17cad09f1ce135074f73e49005b57a784
  stemcell:
    os: ubuntu-xenial
    version: latest
  url: https://github.com/starkandwayne/awscli2-boshrelease/releases/download/v1.0.3/awscli2-1.0.3-ubuntu-xenial-621.125-20220131-124414-425383.tgz
  version: 1.0.3
