---
name: awscli2

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: awscli2
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: awscli2
    release: awscli2
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  version: 0.12.3
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
- name: awscli2
  version: create  # TODO: update after first final release
  url: .           # TODO: update after first final release
  # sha1:            TODO: update after first final release
