---
name: awscliv2

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: awscliv2
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: awscliv2
    release: awscli2
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  url: git+https://github.com/cloudfoundry/bpm-release
  version: 1.1.8
- name: awscli2
  sha1: 9ac67cae872e2180fcd6c74d2969f60f02716434
  url: https://github.com/starkandwayne/awscli2-boshrelease/releases/download/v1.0.0/awscli2-1.0.0.tgz
  version: 1.0.0
