---
name: awscliv2

instance_groups:
- name: awscliv2
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: awscliv2
    release: awscli2
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: awscli2
  sha1: 25daa9e651c10172e3b269cfb9bd125d08203102
  stemcell:
    os: ubuntu-xenial
    version: "621.125"
  url: https://s3.amazonaws.com/awscli2-boshrelease/compiled-releases/awscli2/awscli2-1.0.3-ubuntu-xenial-621.125-20220201-081214-711205.tgz
  version: 1.0.3
