---
name: awscliv2

instance_groups:
- name: awscliv2
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: awscliv2
    release: awscli2
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: awscli2
  sha1: cfb2b10deb3d136dd319f9ba083ffe753a4a2e76
  stemcell:
    os: ubuntu-bionic
    version: "1.107"
  url: https://s3.amazonaws.com/awscli2-boshrelease/compiled-releases/awscli2/awscli2-1.0.5-ubuntu-bionic-1.107-20220930-050313-80968151-20220930050314.tgz
  version: 1.0.5
